"""Pack a whole profile into one file, and unpack it again.

A profile is only partly rows in the database. The rest of it — cookies, local
storage, history, saved logins — lives in a Firefox profile directory, and an
account that has been warmed up for months is mostly that directory. Exporting
the settings alone would move the costume without the memory.

So an archive carries both: the profile record (including the pinned
fingerprint) and the browser data directory. Restoring it elsewhere gives back a
profile that is the same machine *and* still logged in.

Layout of the archive::

    manifest.json   format version and what produced it
    profile.json    the profile record
    data/…          the browser profile directory

The archive is not encrypted. It contains session cookies and the proxy
password, so it is exactly as sensitive as the account it belongs to.
"""

import json
import zipfile
from pathlib import Path
from typing import Any

from loguru import logger

from camoufox_pm import __version__
from camoufox_pm.core.models import Profile

FORMAT_VERSION = 1
MANIFEST_NAME = "manifest.json"
PROFILE_NAME = "profile.json"
DATA_PREFIX = "data/"

# A ceiling on the uncompressed size restored from one archive, so a crafted
# zip cannot fill the disk on import. A real profile is tens of MB even before
# caches are stripped; 4 GB leaves generous headroom while still bounding it.
_MAX_EXTRACTED_BYTES = 2 * 1024 * 1024 * 1024

# The manifest and the profile record are read into memory whole, so they get a
# far tighter ceiling than the data directory. Both are kilobytes in practice;
# without this, a 200 KB archive holding a 200 MB manifest drives the heap past
# 400 MB before anything is validated.
_MAX_METADATA_BYTES = 4 * 1024 * 1024

# Regenerated by the browser on demand, and by far the bulk of the directory —
# a profile is ~50 MB of which ~30 MB is startupCache alone. Excluding these
# costs nothing and keeps archives small enough to move around.
_DISPOSABLE = frozenset(
    {
        "cache2",
        "startupCache",
        "shader-cache",
        "thumbnails",
        "crashes",
        "minidumps",
        "datareporting",
        "saved-telemetry-pings",
        "security_state",
        "sessionstore-backups",
        "lock",
        ".parentlock",
    }
)


def _should_skip(relative: Path) -> bool:
    """Skip disposable caches and the lock files of a running browser."""
    return any(part in _DISPOSABLE for part in relative.parts)


def _copy_bounded(member: Any, handle: Any, budget: int) -> int:
    """Copy ``member`` to ``handle`` in chunks, refusing to exceed ``budget``.

    The up-front size check is not sufficient on its own. A zip may hold several
    members under the same name: the declared total counts each copy once, while
    extraction iterates every entry and resolves each to the same (largest) file,
    so the real total can exceed what was declared. Reading in bounded chunks
    catches that as it happens.

    (A header that simply under-reports its own size is not the gap — CPython
    caps reads at the declared length and fails the CRC.)
    """
    written = 0
    while True:
        chunk = member.read(1 << 20)
        if not chunk:
            return written
        written += len(chunk)
        if written > budget:
            raise ValueError("Profile archive is larger than the import limit")
        handle.write(chunk)


def export_profile(profile: Profile, data_dir: Path, destination: Path) -> Path:
    """Write ``profile`` and its browser data into a zip at ``destination``."""
    manifest = {
        "format_version": FORMAT_VERSION,
        "produced_by": f"camoufox-pm {__version__}",
        "profile_id": profile.id,
        "profile_name": profile.name,
    }
    record = profile.model_dump(mode="json")
    # The id and the on-disk path belong to the instance that exported it; an
    # import assigns its own.
    record.pop("id", None)
    record.pop("storage_path", None)

    written = 0
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        archive.writestr(MANIFEST_NAME, json.dumps(manifest, indent=2))
        archive.writestr(PROFILE_NAME, json.dumps(record, indent=2))

        if data_dir.is_dir():
            for path in sorted(data_dir.rglob("*")):
                if not path.is_file():
                    continue
                relative = path.relative_to(data_dir)
                if _should_skip(relative):
                    continue
                try:
                    archive.write(path, DATA_PREFIX + relative.as_posix())
                    written += 1
                except OSError as exc:  # a file vanished or is locked
                    logger.warning(f"Skipped {relative} while exporting: {exc}")

    logger.info(f"Exported profile {profile.id} with {written} data files")
    return destination


def read_archive(source: Path) -> dict[str, Any]:
    """Return the profile record from an archive, validating its shape."""
    with zipfile.ZipFile(source) as archive:
        names = set(archive.namelist())
        if MANIFEST_NAME not in names or PROFILE_NAME not in names:
            raise ValueError("Not a Camoufox profile archive")

        for name in (MANIFEST_NAME, PROFILE_NAME):
            if archive.getinfo(name).file_size > _MAX_METADATA_BYTES:
                raise ValueError(f"Archive entry {name} is implausibly large")

        manifest = json.loads(archive.read(MANIFEST_NAME))
        version = manifest.get("format_version")
        if version != FORMAT_VERSION:
            raise ValueError(
                f"Unsupported archive format {version}; this build reads version {FORMAT_VERSION}"
            )
        return json.loads(archive.read(PROFILE_NAME))


def extract_data(source: Path, target_dir: Path) -> int:
    """Restore the browser data directory from an archive.

    Entries are placed by resolved path and anything landing outside the target
    is refused, so a crafted archive cannot write elsewhere on the machine.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    resolved_target = target_dir.resolve()
    restored = 0

    with zipfile.ZipFile(source) as archive:
        # Trust the declared sizes only as a first gate; the copy below also stops
        # if a lying header lets the real total run past the ceiling.
        declared = sum(
            info.file_size for info in archive.infolist() if info.filename.startswith(DATA_PREFIX)
        )
        if declared > _MAX_EXTRACTED_BYTES:
            raise ValueError("Profile archive is larger than the import limit")

        budget = _MAX_EXTRACTED_BYTES
        for name in archive.namelist():
            if not name.startswith(DATA_PREFIX) or name.endswith("/"):
                continue
            relative = name[len(DATA_PREFIX) :]
            destination = (target_dir / relative).resolve()
            if not destination.is_relative_to(resolved_target):
                logger.warning(f"Refused archive entry outside the profile: {name}")
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(name) as member, open(destination, "wb") as handle:
                budget -= _copy_bounded(member, handle, budget)
            restored += 1

    logger.info(f"Restored {restored} data files into {target_dir}")
    return restored
